### ISSUE TITLE
Usage clarification for adopt-dev-deps in readme

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#1]
Looks like usage of `adopt-dev-deps topcoder-react-utils` may require clarification in the readme.

I followed readme:
1. Run `npm install --save topcoder-react-utils`
2. Run `adopt-dev-deps topcoder-react-utils` and got an error `-bash: adopt-dev-deps: command not found`.
3. So instead I run `node_modules/topcoder-react-utils/bin/adopt-dev-deps` and it worked.

**Comment by birdofpreyru** [comment]
@maxceem Interesting! As per my understanding of NPM docs, the way it is set up and documented now should work, and it does work for me:
- `adopt-dev-deps` script is added to `bin` map in `package.json`: https://github.com/topcoder-platform/topcoder-react-utils/blob/master/package.json#L2
- And as per https://docs.npmjs.com/files/package.json#bin NPM is supposed to properly link this script so it is found on PATH.

Probably, it is something special about NodeJS / NPM setup on your system? Can you investigate it further? If it is some common pitfal, we sure should mention it in the docs. Otherwise we can instruct to run it as `node_modules/.bin/adopt-dev-deps` or `node_modules/topcoder-react-utils/bin/adopt-dev-deps`, but these are not the best practices, I believe.

**Comment by maxceem** [comment]
Hmm, `node_modules/.bin/adopt-dev-deps` also works for me, so symlink is created as described for a local package.

Could you please share with me, what is the output of the next to commands for you:
- `pwd`
- `which adopt-dev-deps`

**Comment by birdofpreyru** [comment]
Oh, look at this screenshot, it turns out I also have the problem in some cases:
![image](https://user-images.githubusercontent.com/20144632/35513370-125033aa-0503-11e8-9274-965a90698319.png)

Namely, the link to script is found with Node 8.9.4, which is the latest I have onboard, but when I switch to 8.9.2 with NVM, the command is not found anymore, and re-installation of Community App dependencies does not help.

**Comment by maxceem** [comment]
Probably, you used `npm link` command during development which creates a symlink in the global folder listed in `PATH` environment variable.

And after you switched to another node version it which has another folder with global packages, so it's not available anymore.

**Comment by birdofpreyru** [comment]
Yes, @maxceem , it seems to be the case: `npm link` inside `topcoder-react-utils` makes the trick.
So, I guess, the best and correct way is to call it as `./node_modules/.bin/adopt-dev-deps topcoder-react-utils`.

**Comment by maxceem** [comment]
> So, I guess, the best and correct way is to call it as ./node_modules/.bin/adopt-dev-deps topcoder-react-utils.

Yeah, I also don't know a better solution.
