### ISSUE TITLE
[Proposal] Add type property for Button component

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-react-utils#11]
It can be useful to be able to set property `type` for `Button` component. 
For example adding `type="submit"` for buttons enables automatic form submittion when we press `<Enter>` in a form field.

**Comment by birdofpreyru** [comment]
Probably, a `submitForm` flag, rather than `type` param, will be better?

My current thoughts: to make it work both when our `<Button>` renders into `<button>` or `<a>`, we should not rely on `<button>`'s `type` property, but, when we want such behavior, we just prepend `onClick` handler with a simple JS code that lookups the closest enclosing form in the HTML hierarchy and triggers submission?

Also, if we use Redux, using such option seems to be a cheat to me, as it avoids using Redux action. But, yeah, we still can provide such option.

**Comment by maxceem** [comment]
Just in my opinion `type` property would be better than custom `submitForm` as everybody is familiar with that property.
`<Button>` component already has some properties which are only applied to the link only, so having some property which is applied to the `button` only seems ok.

To clarify, it's not enough to handle `onClick` event to implement the behavior I was talking about. I'm talking about form submission when we press `Enter` key in any form field which causes form to submit. To implement it we have to handle `onKeyPress` event for each form field and check whether 'Enter' was pressed.

Regarding Redux, we are not encorouged to cheat here, as we can call the same Redux action on form submit:
```jsx
<form onSubmit={(evt) => {
  evt.preventDefault();
  dispatch(getReduxAction());
}}>
   <input type="text" /> // we press Enter in this field
   <Button type="submit">Submit</Button>
</form>
```

PS. Only downside of having `type` property is that generally we can set it to `reset`. And pressing such button will `clear` all form fields. So probably this values has to be banned in some way. As it would break Redux approach.

**Comment by birdofpreyru** [comment]
Okay, I was saying wrong stuff :)
Feel free to add optional `type` prop as you suggest, and also `onKeyPress` can be added as well.
